# Generated by Django 3.2 on 2024-02-10 17:13

import MoveSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to=MoveSite.models.upload_location)),
                ('realesedYear', models.TextField()),
                ('RunningTime', models.TextField()),
                ('Age', models.IntegerField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Animation', 'Animation')], max_length=10)),
                ('movie', models.FileField(blank=True, null=True, upload_to=MoveSite.models.upload_location)),
            ],
        ),
    ]
